"""Update ML features

Revision ID: 3e484da688bf
Revises: 2c9abcab1f3b
Create Date: 2026-06-28 13:00:39.024996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e484da688bf'
down_revision: Union[str, Sequence[str], None] = '2c9abcab1f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_applications', sa.Column('FLAG_MOBIL', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('FLAG_PHONE', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('FLAG_WORK_PHONE', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('FLAG_CONT_MOBILE', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('FLAG_EMAIL', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('DAYS_EMPLOYED', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('FLAG_OWN_REALTY', sa.String(length=5), nullable=True))
    op.add_column('credit_applications', sa.Column('NAME_HOUSING_TYPE', sa.String(length=50), nullable=True))
    op.add_column('credit_applications', sa.Column('CNT_CHILDREN', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('CNT_FAM_MEMBERS', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('NAME_FAMILY_STATUS', sa.String(length=50), nullable=True))
    op.add_column('credit_applications', sa.Column('DAYS_REGISTRATION', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('DAYS_ID_PUBLISH', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('DAYS_LAST_PHONE_CHANGE', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('REG_REGION_NOT_WORK_REGION', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('REG_CITY_NOT_WORK_CITY', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('LIVE_CITY_NOT_WORK_CITY', sa.Integer(), nullable=True))
    op.add_column('credit_applications', sa.Column('NAME_EDUCATION_TYPE', sa.String(length=100), nullable=True))
    op.add_column('credit_applications', sa.Column('NAME_INCOME_TYPE', sa.String(length=100), nullable=True))
    op.add_column('credit_applications', sa.Column('OCCUPATION_TYPE', sa.String(length=100), nullable=True))
    op.add_column('credit_applications', sa.Column('ORGANIZATION_TYPE', sa.String(length=100), nullable=True))
    op.add_column('credit_applications', sa.Column('REGION_RATING_CLIENT', sa.Integer(), nullable=True))
    op.drop_column('credit_applications', 'credit_history_years')
    op.drop_column('credit_applications', 'fico_score')
    op.drop_column('credit_applications', 'acc_open_past_24mths')
    op.drop_column('credit_applications', 'delinq_2yrs')
    op.drop_column('credit_applications', 'grade')
    op.drop_column('credit_applications', 'inq_last_6mths')
    op.drop_column('credit_applications', 'sub_grade')
    op.drop_column('credit_applications', 'pct_tl_nvr_dlq')
    op.add_column('predictions', sa.Column('financial_index', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('behavioral_index', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('digital_trust_index', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('meta_index', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('alternative_credit_score', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('financial_default_probability', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('behavioral_default_probability', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('digital_default_probability', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('overall_default_probability', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('financial_shap_explanations', sa.JSON(), nullable=True))
    op.add_column('predictions', sa.Column('behavioral_shap_explanations', sa.JSON(), nullable=True))
    op.add_column('predictions', sa.Column('digital_trust_shap_explanations', sa.JSON(), nullable=True))
    op.drop_column('predictions', 'credit_score')
    op.drop_column('predictions', 'model_version')
    op.drop_column('predictions', 'default_probability')
    op.drop_column('predictions', 'top_factors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('top_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('default_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('credit_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('predictions', 'digital_trust_shap_explanations')
    op.drop_column('predictions', 'behavioral_shap_explanations')
    op.drop_column('predictions', 'financial_shap_explanations')
    op.drop_column('predictions', 'overall_default_probability')
    op.drop_column('predictions', 'digital_default_probability')
    op.drop_column('predictions', 'behavioral_default_probability')
    op.drop_column('predictions', 'financial_default_probability')
    op.drop_column('predictions', 'alternative_credit_score')
    op.drop_column('predictions', 'meta_index')
    op.drop_column('predictions', 'digital_trust_index')
    op.drop_column('predictions', 'behavioral_index')
    op.drop_column('predictions', 'financial_index')
    op.add_column('credit_applications', sa.Column('pct_tl_nvr_dlq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('sub_grade', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('inq_last_6mths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('delinq_2yrs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('acc_open_past_24mths', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('fico_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credit_applications', sa.Column('credit_history_years', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('credit_applications', 'REGION_RATING_CLIENT')
    op.drop_column('credit_applications', 'ORGANIZATION_TYPE')
    op.drop_column('credit_applications', 'OCCUPATION_TYPE')
    op.drop_column('credit_applications', 'NAME_INCOME_TYPE')
    op.drop_column('credit_applications', 'NAME_EDUCATION_TYPE')
    op.drop_column('credit_applications', 'LIVE_CITY_NOT_WORK_CITY')
    op.drop_column('credit_applications', 'REG_CITY_NOT_WORK_CITY')
    op.drop_column('credit_applications', 'REG_REGION_NOT_WORK_REGION')
    op.drop_column('credit_applications', 'DAYS_LAST_PHONE_CHANGE')
    op.drop_column('credit_applications', 'DAYS_ID_PUBLISH')
    op.drop_column('credit_applications', 'DAYS_REGISTRATION')
    op.drop_column('credit_applications', 'NAME_FAMILY_STATUS')
    op.drop_column('credit_applications', 'CNT_FAM_MEMBERS')
    op.drop_column('credit_applications', 'CNT_CHILDREN')
    op.drop_column('credit_applications', 'NAME_HOUSING_TYPE')
    op.drop_column('credit_applications', 'FLAG_OWN_REALTY')
    op.drop_column('credit_applications', 'DAYS_EMPLOYED')
    op.drop_column('credit_applications', 'FLAG_EMAIL')
    op.drop_column('credit_applications', 'FLAG_CONT_MOBILE')
    op.drop_column('credit_applications', 'FLAG_WORK_PHONE')
    op.drop_column('credit_applications', 'FLAG_PHONE')
    op.drop_column('credit_applications', 'FLAG_MOBIL')
    # ### end Alembic commands ###
