"""create initial tables

Revision ID: a4f383d9c6d4
Revises: 
Create Date: 2026-06-22 01:43:30.772340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f383d9c6d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('credit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_amnt', sa.Float(), nullable=True),
    sa.Column('annual_inc', sa.Float(), nullable=True),
    sa.Column('dti', sa.Float(), nullable=True),
    sa.Column('installment', sa.Float(), nullable=True),
    sa.Column('fico_score', sa.Integer(), nullable=True),
    sa.Column('tot_cur_bal', sa.Float(), nullable=True),
    sa.Column('revol_util', sa.Float(), nullable=True),
    sa.Column('emp_length', sa.Integer(), nullable=True),
    sa.Column('home_ownership', sa.String(length=30), nullable=True),
    sa.Column('inq_last_6mths', sa.Integer(), nullable=True),
    sa.Column('delinq_2yrs', sa.Integer(), nullable=True),
    sa.Column('pct_tl_nvr_dlq', sa.Float(), nullable=True),
    sa.Column('open_acc', sa.Integer(), nullable=True),
    sa.Column('total_acc', sa.Integer(), nullable=True),
    sa.Column('bc_util', sa.Float(), nullable=True),
    sa.Column('avg_cur_bal', sa.Float(), nullable=True),
    sa.Column('acc_open_past_24mths', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('sub_grade', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('credit_history_years', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('default_probability', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('top_factors', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['credit_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('uploaded_documents')
    op.drop_table('credit_applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
